--- 
    networks: 
      node-network: 
        driver: bridge
    services: 
      mongodb: 
        image: mongo
        networks: 
          - node-network
        ports: 
          - "27017:27017"
        volumes: 
          - "dbdata:/data/db"
      knowledge-review-server: 
        build: 
          context: "."
        depends_on: 
          - mongodb
        environment: 
          - "MONGODB_URL=mongodb://mongodb:27017/todolist"
        image: knowledge-review-server
        networks: 
          - node-network
        ports: 
          - "5000:5000"
        volumes: 
          - ".:/usr/src/node-server"
    version: "3"
    volumes: 
      dbdata: ~