---
networks:
  node-network:
    driver: bridge

services:
  mongodb:
    image: mongo
    networks:
      - node-network
    ports:
      - '27017:27017'
    volumes:
      - 'dbdata:/data/db'
  netflix-clone:
    build:
      context: '.'
    restart: always
    depends_on:
      - mongodb
    environment:
      - 'MONGODB_URL=mongodb://mongodb:27017/flix'
    image: netflix-clone
    networks:
      - node-network
    ports:
      - '5000:5000'
    volumes:
      - '.:/usr/node-server/src'
version: '3'

volumes:
  dbdata: ~
